/**
 * Frontend Configuration for Lung Cancer Predictor
 * Centralized API base URL and endpoint definitions.
 */

const CONFIG = {
  // Default API base URL (defaults to window.location.origin if served by backend, or localhost:8000)
  API_BASE_URL:
    window.location.port === "8000" || window.location.port === "5000"
      ? window.location.origin
      : "http://127.0.0.1:8000",

  ENDPOINTS: {
    HEALTH: "/health",
    MODEL_INFO: "/model-info",
    PREDICT: "/predict",
  },

  // UI / Presentation Constants
  DECISION_THRESHOLD: 0.50,
  MODEL_NAME: "Logistic Regression (Balanced, C=0.1)",
  APP_TITLE: "Lung Cancer Predictor",
  APP_SUBTITLE: "Academic Machine Learning Prediction System — Not a Medical Diagnostic Tool",
  DISCLAIMER_TEXT: "This result is generated by an academic machine learning model and must not be used as a medical diagnosis or substitute for professional medical advice.",
};

// Freeze configuration to prevent accidental modification
Object.freeze(CONFIG);
Object.freeze(CONFIG.ENDPOINTS);
