import React, { useRef, useState } from 'react';
import { ArrowRight, ChevronLeft, ChevronRight } from 'lucide-react';
import { IMAGES } from '../../constants/images';
import { useInView } from '../ui/Motion';

const structures = [
  { id: 'bronchial-tree', number: '01', name: 'Bronchial tree', category: 'Structure', metadata: 'Air conduction', description: 'The trachea divides into right and left main bronchi, then progressively smaller airways that distribute inhaled air through the lungs.', function: 'Air conduction', connectedTo: 'Lobes', context: 'The branching airways distribute air through the lungs.' , x: 39, y: 28 },
  { id: 'lobes', number: '02', name: 'Lobes', category: 'Structure', metadata: 'Lung organization', description: 'The right lung has three lobes and the left lung has two. These divisions are part of the lung’s normal anatomical organization.', function: 'Lung organization', connectedTo: 'Alveoli', context: 'Lobar structure helps organize how air is distributed through the lungs.', x: 64, y: 40 },
  { id: 'alveoli', number: '03', name: 'Alveoli', category: 'Physiology', metadata: 'Gas exchange', description: 'Alveoli are small air spaces where oxygen and carbon dioxide exchange occurs across a thin membrane.', function: 'Gas exchange', connectedTo: 'Capillary network', context: 'Their thin surfaces support exchange between air and blood.', x: 31, y: 66 },
  { id: 'capillary-network', number: '04', name: 'Capillary network', category: 'Physiology', metadata: 'Blood interface', description: 'Pulmonary capillaries surround alveoli, enabling blood-gas exchange between the lungs and circulation.', function: 'Blood interface', connectedTo: 'Blood exchange', context: 'Capillaries provide the blood-side interface for gas exchange.', x: 68, y: 69 },
];

export default function LungEducation() {
  const [ref, visible] = useInView(); const [active, setActive] = useState(0); const buttons = useRef([]); const selected = structures[active];
  const move = (direction) => { const next = (active + direction + structures.length) % structures.length; setActive(next); buttons.current[next]?.focus(); };
  const keys = (event) => { if (event.key === 'ArrowRight' || event.key === 'ArrowDown') { event.preventDefault(); move(1); } if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') { event.preventDefault(); move(-1); } };
  return <section id="education" ref={ref} className={`anatomy-explorer ${visible ? 'is-visible' : ''}`} aria-labelledby="anatomy-title"><div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-12">
    <header className="anatomy-heading"><p className="eyebrow anatomy-enter anatomy-enter-1">Respiratory anatomy</p><h2 id="anatomy-title" className="anatomy-title anatomy-enter anatomy-enter-2">See the lung as a connected system.</h2><p className="anatomy-intro anatomy-enter anatomy-enter-3">Explore how airways, lobes, alveoli, and surrounding capillary networks work together to support gas exchange.</p></header>
    <div className="anatomy-layout anatomy-enter anatomy-enter-4"><div className={`anatomy-atlas anatomy-active-${active}`} aria-label="Interactive lung anatomy visualization"><div className="anatomy-atlas-top"><span>INTERACTIVE LUNG VISUAL</span><span>EXPLORING {selected.number} / 04 — {selected.name}</span></div><img src={IMAGES.lungAnatomy} alt="Illustrated human lung anatomy" className="anatomy-image" /><div className="anatomy-atmosphere" /><div className="anatomy-region" aria-hidden="true" /><svg className="anatomy-paths" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path className={active >= 1 ? 'is-complete' : ''} d="M39 28 C48 29, 56 33, 64 40" /><path className={active >= 2 ? 'is-complete' : ''} d="M64 40 C52 49, 40 58, 31 66" /><path className={active >= 3 ? 'is-complete' : ''} d="M31 66 C43 69, 55 70, 68 69" /></svg><div className="anatomy-nodes" onKeyDown={keys}>{structures.map((item, index) => <button key={item.id} ref={(node) => { buttons.current[index] = node; }} type="button" onClick={() => setActive(index)} className={`anatomy-node ${active === index ? 'is-active' : ''} ${index < active ? 'is-complete' : ''}`} style={{ '--x': `${item.x}%`, '--y': `${item.y}%`, '--delay': `${index * 90}ms` }} aria-label={`Explore ${item.name}`} aria-selected={active === index} aria-controls="anatomy-information"><span className="anatomy-node-point" /><span className="anatomy-node-label"><b>{item.number}</b><strong>{item.name}</strong><small>{item.metadata}</small></span></button>)}</div><div className="anatomy-flow"><span>Airway</span><ArrowRight /><span>Lobe</span><ArrowRight /><span>Alveolus</span><ArrowRight /><span>Blood exchange</span><i aria-hidden="true" /></div></div>
      <aside id="anatomy-information" className="anatomy-info" aria-live="polite"><div className="anatomy-info-top"><span>{selected.number} / 04</span><span>{selected.category}</span></div><h3 key={`name-${active}`}>{selected.name}</h3><p key={`description-${active}`} className="anatomy-description">{selected.description}</p><dl><div><dt>Function</dt><dd>{selected.function}</dd></div><div><dt>Connected system</dt><dd>{selected.connectedTo}</dd></div><div><dt>Why it matters</dt><dd>{selected.context}</dd></div></dl><div className="anatomy-info-meta"><span>{selected.category}</span><span>{selected.metadata}</span></div></aside></div>
    <div className="anatomy-navigation" role="tablist" aria-label="Anatomy structures">{structures.map((item, index) => <button type="button" key={item.id} role="tab" aria-selected={active === index} onClick={() => setActive(index)} className={`anatomy-nav-item ${active === index ? 'is-active' : ''} ${index < active ? 'is-complete' : ''}`}><span>{item.number}</span><strong>{item.name}</strong><i /></button>)}</div><p className="anatomy-disclaimer">This anatomical atlas is educational and separate from the survey-based prediction model. Anatomy selections do not change a prediction.</p><div className="anatomy-step-controls"><button type="button" onClick={() => move(-1)} aria-label="Previous anatomy structure"><ChevronLeft className="h-4 w-4" /> Previous</button><button type="button" onClick={() => move(1)}>Next structure <ChevronRight className="h-4 w-4" /></button></div>
  </div></section>;
}
