import React, { useMemo, useState } from 'react';

const factors = [
  ['ALLERGY', 'Allergic sensitivities', .5214, 1.6844], ['ALCOHOL_CONSUMING', 'Alcohol consumption', .4821, 1.6195], ['SWALLOWING_DIFFICULTY', 'Swallowing difficulty', .4533, 1.5735], ['WHEEZING', 'Wheezing', .4312, 1.5391], ['COUGHING', 'Persistent coughing', .3927, 1.4810], ['CHEST_PAIN', 'Chest pain', .3218, 1.3796], ['PEER_PRESSURE', 'Peer pressure', .3105, 1.3641], ['YELLOW_FINGERS', 'Yellow fingers', .3012, 1.3515], ['FATIGUE', 'Fatigue', .2514, 1.2858], ['ANXIETY', 'Anxiety', .2318, 1.2609], ['CHRONIC_DISEASE', 'Chronic disease', .1824, 1.2001], ['AGE', 'Age', .1512, 1.1632], ['GENDER', 'Gender', .1124, 1.1190], ['SMOKING', 'Smoking', .0841, 1.0877], ['SHORTNESS_OF_BREATH', 'Shortness of breath', .0712, 1.0738],
];
export default function RiskFactors() {
  const [metric, setMetric] = useState('odds'); const [active, setActive] = useState(0);
  const maximum = metric === 'odds' ? 1.6844 : .5214; const selected = factors[active];
  const values = useMemo(() => factors.map((f) => metric === 'odds' ? f[3] : f[2]), [metric]);
  return <section id="risk-factors" className="section-space bg-pearl-100 border-y border-pearl-300"><div className="max-w-7xl mx-auto px-6 sm:px-8 lg:px-12">
    <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="eyebrow">Model association explorer</p><h2 className="section-title">Explore fitted feature associations.</h2><p className="section-copy">These standardized coefficients and odds ratios are from the frozen logistic regression model. They describe model association, not causal medical effects.</p></div><div className="inline-flex self-start border border-pearl-300 bg-white p-1" aria-label="Choose chart metric"><button onClick={() => setMetric('odds')} aria-pressed={metric === 'odds'} className={`min-h-10 px-4 text-caption font-bold ${metric === 'odds' ? 'bg-ink-900 text-white' : 'text-pearl-700'}`}>Odds ratio</button><button onClick={() => setMetric('beta')} aria-pressed={metric === 'beta'} className={`min-h-10 px-4 text-caption font-bold ${metric === 'beta' ? 'bg-ink-900 text-white' : 'text-pearl-700'}`}>Coefficient β</button></div></div>
    <div className="mt-10 grid lg:grid-cols-[1fr_320px] border border-pearl-300 bg-white"><div className="p-4 sm:p-7"><div className="mb-4 flex justify-between text-caption font-mono uppercase text-pearl-600"><span>Feature</span><span>{metric === 'odds' ? 'OR = exp(β)' : 'Standardized log-odds β'}</span></div><div className="space-y-1">{factors.map((factor, index) => { const value = values[index]; return <button key={factor[0]} onClick={() => setActive(index)} className={`risk-row group ${active === index ? 'is-active' : ''}`}><span className="truncate text-caption font-bold text-ink-900">{String(index + 1).padStart(2, '0')} {factor[1]}</span><span className="h-2 overflow-hidden bg-pearl-200"><span className="block h-full origin-left bg-ink-900 transition-transform duration-500 group-hover:bg-clinical-600" style={{ transform: `scaleX(${value / maximum})` }} /></span><span className="font-mono text-caption font-bold text-ink-900">{value.toFixed(metric === 'odds' ? 2 : 4)}</span></button> })}</div></div><aside className="border-t border-pearl-300 bg-pearl-100 p-6 lg:border-l lg:border-t-0"><span className="font-mono text-caption text-clinical-700">SELECTED FEATURE</span><h3 className="mt-2 text-xl font-bold text-ink-900">{selected[1]}</h3><dl className="mt-6 space-y-4"><div><dt className="text-caption uppercase text-pearl-600">Coefficient</dt><dd className="font-mono text-2xl font-extrabold text-ink-900">β = +{selected[2].toFixed(4)}</dd></div><div><dt className="text-caption uppercase text-pearl-600">Odds ratio</dt><dd className="font-mono text-2xl font-extrabold text-clinical-800">{selected[3].toFixed(4)}</dd></div></dl><p className="mt-6 border-t border-pearl-300 pt-4 text-caption leading-relaxed text-pearl-700">Relative feature contribution within this fitted model. <strong>Model association, not causal effect.</strong></p></aside></div>
  </div></section>;
}
