import React, { useRef, useState } from 'react';
import { ArrowDown, ArrowUpRight } from 'lucide-react';
import { useInView } from '../ui/Motion';

const stages = [
  { id: 'signal', title: 'Early clinical awareness', path: 'Signal', summary: 'Notice a change, then give it appropriate clinical attention.', detail: 'Recognizing changes in respiratory wellbeing can support timely conversations with a qualified clinician. It is not a diagnosis and does not determine a cause.', visual: 'Observed change' },
  { id: 'context', title: 'Multi-factor risk assessment', path: 'Context', summary: 'One signal becomes more useful when considered alongside its context.', detail: 'A structured profile can organize demographic and survey indicators without treating a single factor as decisive or causal.', visual: 'Structured context' },
  { id: 'evidence', title: 'Evidence-informed consultation', path: 'Evidence', summary: 'Clear histories make health conversations more focused.', detail: 'Symptom timelines and relevant context can help make a consultation more focused and productive.', visual: 'Evidence record' },
  { id: 'interpretation', title: 'Transparent statistical reasoning', path: 'Interpretation', summary: 'A transparent model output is a research aid, not a clinical verdict.', detail: 'LungSense exposes its inputs, threshold, and evaluation boundaries so users can explore a research-oriented statistical workflow.', visual: 'Bounded output' },
];

export default function WhyItMatters() {
  const [ref, visible] = useInView(); const [active, setActive] = useState(0); const stageRefs = useRef([]); const current = stages[active];
  const move = (direction) => { const next = (active + direction + stages.length) % stages.length; setActive(next); stageRefs.current[next]?.focus(); };
  const onKeyDown = (event) => { if (event.key === 'ArrowRight' || event.key === 'ArrowDown') { event.preventDefault(); move(1); } if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') { event.preventDefault(); move(-1); } };
  return <section id="why-it-matters" ref={ref} className={`reasoning-section ${visible ? 'is-visible' : ''}`} aria-labelledby="reasoning-title"><div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-12">
    <header className="reasoning-header"><p className="eyebrow reasoning-enter reasoning-enter-1">Clinical significance</p><h2 id="reasoning-title" className="reasoning-title reasoning-enter reasoning-enter-2">Why earlier attention matters.</h2><p className="reasoning-intro reasoning-enter reasoning-enter-3">LungSense is designed to move from an observed signal through context and evidence toward a transparent, research-oriented interpretation.</p></header>
    <div className="reasoning-layout reasoning-enter reasoning-enter-4">
      <div className="reasoning-visual" aria-label="Conceptual research pathway visualization"><div className="reasoning-visual-top"><span className="font-mono text-caption text-clinical-700">CONCEPTUAL RESEARCH PATHWAY</span><span className="font-mono text-caption text-pearl-500">0{active + 1} / 04</span></div><div className="signal-field"><span className="signal-label">RESPIRATORY SIGNAL</span><span className="signal-line" /><span className="signal-node" style={{ '--node': active }} /><span className="signal-change">change</span></div><div className="reasoning-layers">{stages.map((stage, index) => <div key={stage.id} className={`reasoning-layer ${index === active ? 'is-active' : ''} ${index < active ? 'is-complete' : ''}`}><span>{String(index + 1).padStart(2, '0')}</span><strong>{stage.path}</strong><i /></div>)}</div><div className="reasoning-visual-readout"><span>{current.visual}</span><ArrowDown className="h-4 w-4" /><strong>{current.path}</strong></div></div>
      <div className="reasoning-content"><div className="reasoning-stage-nav" role="tablist" aria-label="Reasoning stages" onKeyDown={onKeyDown}>{stages.map((stage, index) => <button key={stage.id} ref={(node) => { stageRefs.current[index] = node; }} type="button" role="tab" aria-selected={active === index} aria-controls="reasoning-panel" tabIndex={active === index ? 0 : -1} onClick={() => setActive(index)} className={`reasoning-stage ${active === index ? 'is-active' : ''} ${index < active ? 'is-complete' : ''}`}><span className="reasoning-stage-index">0{index + 1}</span><span><strong>{stage.title}</strong><small>{stage.path}</small></span><ArrowUpRight className="h-4 w-4" /></button>)}</div><div id="reasoning-panel" role="tabpanel" className="reasoning-panel" aria-live="polite"><span className="font-mono text-caption text-clinical-700">ACTIVE STAGE — 0{active + 1}</span><h3 key={`title-${active}`}>{current.title}</h3><p key={`summary-${active}`} className="reasoning-summary">{current.summary}</p><p key={`detail-${active}`} className="reasoning-detail">{current.detail}</p><div className="reasoning-progress"><span>Signal</span><i style={{ transform: `scaleX(${(active + 1) / stages.length})` }} /><span>Interpretation</span></div></div></div>
    </div><p className="reasoning-note"><strong>Educational context only.</strong> This pathway explains a research and consultation-oriented way of organizing information. It does not provide a medical diagnosis.</p>
  </div></section>;
}
